local c = require "colors.solarized_dark.palette"

local M = {}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.apply()
  hi("Normal", { fg = c.base0, bg = "NONE" })
  hi("NormalNC", { fg = c.base0, bg = "NONE" })
  hi("NormalFloat", { fg = c.base0, bg = "NONE" })
  hi("FloatBorder", { fg = c.cyan, bg = "NONE" })
  hi("FloatTitle", { fg = c.cyan, bg = "NONE" })
  hi("SignColumn", { bg = "NONE" })
  hi("FoldColumn", { fg = c.base01, bg = "NONE" })
  hi("EndOfBuffer", { fg = c.base03, bg = "NONE" })

  hi("ColorColumn", { bg = c.base02 })
  hi("CursorColumn", { bg = c.base02 })
  hi("Cursor", { fg = c.base03, bg = c.cursor })
  hi("CursorLine", { bg = c.base02 })
  hi("CursorLineNr", { fg = c.magenta, bg = "NONE" })
  hi("LineNr", { fg = c.base01, bg = "NONE" })
  hi("MatchParen", { fg = c.cyan, bg = c.base02, bold = true })
  hi("NonText", { fg = c.base01, bg = "NONE" })
  hi("Pmenu", { fg = c.base1, bg = c.ui_panel })
  hi("PmenuSel", { fg = c.base2, bg = c.ui_select })
  hi("PmenuSbar", { bg = c.ui_panel })
  hi("PmenuThumb", { bg = c.base01 })
  hi("Search", { fg = c.base03, bg = c.yellow })
  hi("IncSearch", { fg = c.base03, bg = c.orange })
  hi("Substitute", { fg = c.base03, bg = c.cyan })
  hi("StatusLine", { fg = c.base1, bg = c.ui_panel })
  hi("StatusLineNC", { fg = c.base01, bg = c.ui_panel })
  hi("TabLine", { fg = c.base1, bg = c.ui_hover_light })
  hi("TabLineFill", { bg = "NONE" })
  hi("TabLineSel", { fg = c.base2, bg = "NONE" })
  hi("VertSplit", { fg = c.ui_panel, bg = "NONE" })
  hi("Visual", { bg = c.selection })
  hi("Whitespace", { link = "NonText" })
  hi("WinSeparator", { fg = c.ui_panel, bg = "NONE" })
  hi("Directory", { fg = c.blue })
  hi("QuickFixLine", { bg = c.selection, bold = true })
  hi("Title", { fg = c.blue, bold = true })
  hi("WinBar", { fg = c.base1, bg = "NONE" })
  hi("WinBarNC", { fg = c.base01, bg = "NONE" })
  hi("SpellBad", { sp = c.red, undercurl = true })
  hi("SpellCap", { sp = c.blue, undercurl = true })
  hi("SpellLocal", { sp = c.cyan, undercurl = true })
  hi("SpellRare", { sp = c.violet, undercurl = true })

  hi("Comment", { fg = c.base01, italic = true })
  hi("Constant", { fg = c.yellow })
  hi("String", { fg = c.cyan })
  hi("Character", { fg = c.orange })
  hi("Number", { fg = c.magenta })
  hi("Boolean", { fg = c.yellow })
  hi("Float", { fg = c.magenta })
  hi("Identifier", { fg = c.blue })
  hi("Function", { fg = c.blue })
  hi("Statement", { fg = c.green })
  hi("Conditional", { fg = c.green })
  hi("Repeat", { fg = c.green })
  hi("Label", { fg = c.green })
  hi("Operator", { fg = c.base0 })
  hi("Keyword", { fg = c.green })
  hi("Exception", { fg = c.green })
  hi("PreProc", { fg = c.yellow })
  hi("Include", { fg = c.blue })
  hi("Define", { fg = c.yellow })
  hi("Macro", { fg = c.yellow })
  hi("PreCondit", { fg = c.yellow })
  hi("Type", { fg = c.orange })
  hi("StorageClass", { fg = c.base1, bold = true })
  hi("Structure", { fg = c.orange })
  hi("Typedef", { fg = c.orange })
  hi("Special", { fg = c.orange })
  hi("SpecialChar", { fg = c.orange })
  hi("Tag", { fg = c.blue })
  hi("Delimiter", { fg = c.base0 })
  hi("SpecialComment", { fg = c.base01, italic = true })
  hi("Debug", { fg = c.red })
  hi("Underlined", { fg = c.violet, underline = true })
  hi("Ignore", { fg = c.base01 })
  hi("Error", { fg = c.red })
  hi("Todo", { fg = c.magenta, bold = true })

  hi("DiffAdd", { fg = c.green, bg = "NONE" })
  hi("DiffChange", { fg = c.orange, bg = "NONE" })
  hi("DiffDelete", { fg = c.red, bg = "NONE" })
  hi("DiffText", { fg = c.blue, bg = "NONE" })

  hi("DiagnosticError", { fg = c.red })
  hi("DiagnosticWarn", { fg = c.yellow })
  hi("DiagnosticInfo", { fg = c.blue })
  hi("DiagnosticHint", { fg = c.cyan })
  hi("DiagnosticOk", { fg = c.green })
  hi("DiagnosticVirtualTextError", { fg = c.red, bg = "NONE" })
  hi("DiagnosticVirtualTextWarn", { fg = c.yellow, bg = "NONE" })
  hi("DiagnosticVirtualTextInfo", { fg = c.blue, bg = "NONE" })
  hi("DiagnosticVirtualTextHint", { fg = c.cyan, bg = "NONE" })
  hi("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
  hi("DiagnosticUnderlineWarn", { sp = c.yellow, undercurl = true })
  hi("DiagnosticUnderlineInfo", { sp = c.blue, undercurl = true })
  hi("DiagnosticUnderlineHint", { sp = c.cyan, undercurl = true })
  hi("DiagnosticDeprecated", { strikethrough = true })
  hi("DiagnosticUnnecessary", { fg = c.base01 })

  hi("GitSignsAdd", { fg = c.green, bg = "NONE" })
  hi("GitSignsChange", { fg = c.orange, bg = "NONE" })
  hi("GitSignsDelete", { fg = c.red, bg = "NONE" })

  hi("RainbowDelimiterRed", { fg = c.bracket1 })
  hi("RainbowDelimiterYellow", { fg = c.yellow })
  hi("RainbowDelimiterBlue", { fg = c.magenta })
  hi("RainbowDelimiterOrange", { fg = c.bracket1 })
  hi("RainbowDelimiterGreen", { fg = c.yellow })
  hi("RainbowDelimiterViolet", { fg = c.magenta })
  hi("RainbowDelimiterCyan", { fg = c.bracket1 })

  hi("@comment", { link = "Comment" })
  hi("@comment.documentation", { link = "SpecialComment" })
  hi("@character", { link = "Character" })
  hi("@character.special", { link = "SpecialChar" })
  hi("@string", { link = "String" })
  hi("@string.documentation", { link = "String" })
  hi("@string.escape", { link = "SpecialChar" })
  hi("@string.regexp", { fg = c.red })
  hi("@string.special", { link = "SpecialChar" })
  hi("@string.special.url", { link = "Underlined" })
  hi("@number", { link = "Number" })
  hi("@number.float", { link = "Float" })
  hi("@boolean", { link = "Boolean" })
  hi("@constant", { link = "Constant" })
  hi("@constant.builtin", { fg = c.yellow })
  hi("@constant.macro", { fg = c.yellow })
  hi("@variable", { fg = c.blue })
  hi("@variable.builtin", { fg = c.blue })
  hi("@variable.parameter", { fg = c.base0 })
  hi("@variable.parameter.builtin", { link = "@variable.parameter" })
  hi("@variable.member", { link = "@property" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@function.builtin", { fg = c.blue })
  hi("@function.macro", { link = "Macro" })
  hi("@function.method", { link = "@function" })
  hi("@function.method.call", { link = "@function.call" })
  hi("@constructor", { fg = c.orange })
  hi("@keyword", { link = "Keyword" })
  hi("@keyword.function", { fg = c.green })
  hi("@keyword.operator", { fg = c.green })
  hi("@keyword.import", { fg = c.blue })
  hi("@keyword.conditional", { link = "@keyword" })
  hi("@keyword.conditional.ternary", { link = "@keyword.conditional" })
  hi("@keyword.coroutine", { link = "@keyword" })
  hi("@keyword.debug", { link = "Debug" })
  hi("@keyword.directive", { link = "PreProc" })
  hi("@keyword.exception", { link = "Exception" })
  hi("@keyword.modifier", { link = "StorageClass" })
  hi("@keyword.repeat", { link = "Repeat" })
  hi("@keyword.return", { link = "@keyword" })
  hi("@keyword.type", { link = "@keyword" })
  hi("@label", { link = "Label" })
  hi("@type", { fg = c.orange })
  hi("@type.builtin", { fg = c.green })
  hi("@type.definition", { fg = c.orange })
  hi("@module", { fg = c.orange })
  hi("@module.builtin", { link = "@module" })
  hi("@property", { fg = c.green })
  hi("@lsp.type.boolean", { link = "@boolean" })
  hi("@lsp.type.class", { link = "@type" })
  hi("@lsp.type.enum", { link = "@type" })
  hi("@lsp.type.enumMember", { link = "@constant" })
  hi("@lsp.type.function", { link = "@function" })
  hi("@lsp.type.interface", { link = "@type" })
  hi("@lsp.type.macro", { link = "@function.macro" })
  hi("@lsp.type.method", { link = "@function.method" })
  hi("@lsp.type.namespace", { link = "@module" })
  hi("@lsp.type.number", { link = "@number" })
  hi("@lsp.type.operator", { link = "@operator" })
  hi("@lsp.type.parameter", { link = "@variable.parameter" })
  hi("@lsp.type.property", { link = "@property" })
  hi("@lsp.type.regexp", { link = "@string.regexp" })
  hi("@lsp.type.string", { link = "@string" })
  hi("@lsp.type.struct", { link = "@type" })
  hi("@lsp.type.type", { link = "@type" })
  hi("@lsp.type.typeParameter", { link = "@type" })
  hi("@lsp.type.variable", { link = "@variable" })
  hi("@tag", { fg = c.blue })
  hi("@tag.attribute", { fg = c.base1 })
  hi("@tag.delimiter", { fg = c.base01 })
  hi("@punctuation", { fg = c.base0 })
  hi("@punctuation.bracket", { fg = c.base0 })
  hi("@punctuation.delimiter", { fg = c.base0 })
  hi("@punctuation.special", { link = "Special" })
  hi("@operator", { link = "Operator" })
  hi("@markup.heading", { fg = c.blue, bold = true })
  hi("@markup.raw", { fg = c.cyan })
  hi("@markup.list", { fg = c.yellow })
  hi("@markup.quote", { fg = c.green })
  hi("@markup.strong", { bold = true })
  hi("@markup.italic", { italic = true })
  hi("@diff.plus", { fg = c.green })
  hi("@diff.minus", { fg = c.red })
  hi("@diff.delta", { fg = c.orange })
end

return M
